[package]
name = "nyarr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.24"
sha2 = "0.10.2"
tar = "0.4.38"

[dev-dependencies]
hexdump = { path = "../hexdump" }
